version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    container_name: db_projet
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=legal_pilot
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - dev
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: src
    container_name: docker_symfony_files
    ports:
      - "8000:80"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
    restart: always
    networks:
      - dev

volumes:
  db-data:

networks:
    dev:
